### ISSUE TITLE
hystrix dashboard does not support cluster that has more than 1 instance

### ISSUE THREAD

**Issue by jicui** [spring-attic/traveler#34]
push agency app with more 2 instance
`---
applications:
  - name: agency
    instances: 2
    memory: 1G
`

name      requested state   instances   memory   disk   urls
agency    started           2/2         1G       1G    
company   started           1/1         1G       1G     

but hystrix dashboard only display one host not two

**Comment by jicui** [comment]
![Screen Shot 2019-12-11 at 9 14 44 AM](https://user-images.githubusercontent.com/1303275/70582848-d8b70800-1bf6-11ea-88f5-8ad211d4034f.png)

**Comment by csterwa** [comment]
@jicui this is a great catch that we hadn't seen previously over all the years it has been released. Unfortunately, we will not be making any new updates to the `p-circuit-breaker-dashboard` service since the Netflix OSS Hystrix Dashboard is in maintenance mode now. Here is an article that describes the current plans for SCS going forward: https://content.pivotal.io/practitioners/replacing-the-spring-cloud-services-circuit-breaker-dashboard
